name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run test
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test images
          path: |
            test/actual.png
            test/expected.png
          retention-days: 5
